### ISSUE TITLE
Apple Pay - The amount contains an invalid currency.

### ISSUE THREAD

**Issue by SjamonDaal** [0100Dev/WHMCS-Mollie#58]
When I process an order with Apple Pay the following error occurs.

```
Mollie\Api\Exceptions\ApiException: Error executing API call (422: Unprocessable Entity): The amount contains an invalid currency. Field: amount.currency. Documentation: https://docs.mollie.com/guides/handling-errors in /var/www/sdhd_hosting/modules/gateways/mollie/vendor/mollie/mollie-api-php/src/Exceptions/ApiException.php:98
Stack trace:
#0 /var/www/sdhd_hosting/modules/gateways/mollie/vendor/mollie/mollie-api-php/src/MollieApiClient.php(484): Mollie\Api\Exceptions\ApiException::createFromResponse(Object(GuzzleHttp\Psr7\Response))
#1 /var/www/sdhd_hosting/modules/gateways/mollie/vendor/mollie/mollie-api-php/src/MollieApiClient.php(456): Mollie\Api\MollieApiClient->parseResponseBody(Object(GuzzleHttp\Psr7\Response))
#2 /var/www/sdhd_hosting/modules/gateways/mollie/vendor/mollie/mollie-api-php/src/MollieApiClient.php(404): Mollie\Api\MollieApiClient->performHttpCallToFullUrl('POST', 'https://api.mol...', '{"amount":{"val...')
#3 /var/www/sdhd_hosting/modules/gateways/mollie/vendor/mollie/mollie-api-php/src/Endpoints/EndpointAbstract.php(76): Mollie\Api\MollieApiClient->performHttpCall('POST', 'payments', '{"amount":{"val...')
#4 /var/www/sdhd_hosting/modules/gateways/mollie/vendor/mollie/mollie-api-php/src/Endpoints/PaymentEndpoint.php(52): Mollie\Api\Endpoints\EndpointAbstract->rest_create(Array, Array)
#5 /var/www/sdhd_hosting/modules/gateways/mollie/mollie.php(90): Mollie\Api\Endpoints\PaymentEndpoint->create(Array)
#6 /var/www/sdhd_hosting/modules/gateways/mollieapplepay_devapp.php(21): mollie_link(Array, 'applepay')
#7 /var/www/sdhd_hosting/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): mollieapplepay_devapp_link(Array)
#8 /var/www/sdhd_hosting/vendor/whmcs/whmcs-foundation/lib/Module/Gateway.php(0): WHMCS\Module\AbstractModule->call('link', Array)
#9 /var/www/sdhd_hosting/vendor/whmcs/whmcs-foundation/lib/Invoice.php(0): WHMCS\Module\Gateway->call('link', Array)
#10 /var/www/sdhd_hosting/viewinvoice.php(0): WHMCS\Invoice->getPaymentLink()
#11 {main}

```

**Comment by SjamonDaal** [comment]
This issue can be closed. This error occured because of a incorrect "Currency Code" of the currency in WHMCS. For Euro use `EUR` and not your country code. 😃
